accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginView, name='login'),
]

chats/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('index', views.index, name='home'),
    path('options',views.options,name='options'),
    path('appointment',views.appointment,name='appointment'),
    path('diabetes',views.diabetes,name='diabetes'),
    path('predict2',views.predict2,name='predict2'),
    path('heart',views.heart,name='heart'),
    path('predict',views.predict,name='predict'),
    path('predict1',views.predict1,name='predict1'),
    path('liver',views.liver,name='liver'),
    path('kidney',views.kidney,name='kidney'),
    path('predict3',views.predict3, name='predict3'),
    path('brain',views.brain,name='brain'),
    path('<str:username>/', views.chatPage, name='chat'),
]

pocketdoc/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('chats.urls')),
    
   
]


templates/appointment.html
{% load static %}
{% load fontawesome_5 %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
{% fontawesome_5_static %}
<link href="{% static 'w3.css' %}" rel="stylesheet" />
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

/* Style inputs */
input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

/* Style the container/contact section */
.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 10px;
}

/* Create two columns that float next to eachother */
.column {
  float: left;
  width: 50%;
  margin-top: 6px;
  padding: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}
</style>
</head>
<body>
   
        <div class="w3-bar w3-black w3-padding-24" style="font-size:20px;">
          <a href="{% url 'home' %}" class="w3-bar-item w3-button" >Home</a>
          <a href="{% url 'diabetes' %}" class="w3-bar-item w3-button" >Diabetes</a>
          <a href="{% url 'heart' %}" class="w3-bar-item w3-button">Heart</a>
          <a href="{% url 'liver' %}" class="w3-bar-item w3-button">Liver Disease</a>
          <a href="{% url 'kidney' %}" class="w3-bar-item w3-button">Kidney Disease</a>
          <a href="" class="w3-bar-item w3-button">Brain Tumor</a>
      
          
       
      </div>
      
<div class="container">
  <div style="text-align:center">
    <h2>Book your Appointment</h2>
   
  </div>
  <div class="row">
    <div class="column">
      <img src="{% static  'pocketdoc.jpg' %}" style="width:100%">
    </div>
    <div class="column">
      <form action="post">
        <label for="fname">First Name</label>
        <input type="text" id="fname" name="firstname" placeholder="Your name..">
        <label for="lname">Last Name</label>
        <input type="text" id="lname" name="lastname" placeholder="Your last name..">
        <label for="country">Department</label>
        <select id="country" name="General">
          <option value="australia">General Services</option>
          <option value="canada">Cardiology</option>
          <option value="usa">Chemoterapy</option>
          <option value="usa">kidney</option>
          <option value="usa">Diabities</option>
        </select>
        <label for="subject">State your Problem</label>
        <textarea id="subject" name="subject" placeholder="Write something.." style="height:170px"></textarea>

        <input type="submit" id="submit" value="Submit">

        <script>
            document.getElementById("submit").addEventListener("click", function(){
                alert("Message Sent Sucessful we have send you a mail " );
            }); 
        </script>
      </form>
    </div>
  </div>
</div>

</body>
</html>

templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" />
    {% block css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}
</body>

</html>

templates/diabetes.html
{% load static %}
{% load fontawesome_5 %}
 
<!DOCTYPE html>
<html>
    <head>
<title>Pocketdoc</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'w3.css' %}" rel="stylesheet" />

{% fontawesome_5_static %}
</head>
<body>

  <div class="w3-bar w3-black w3-padding-24" style="font-size:20px;">
    <a href="{% url 'home' %}" class="w3-bar-item w3-button" >Home</a>
    <a href="{% url 'diabetes' %}" class="w3-bar-item w3-button" >Diabetes</a>
    <a href="{% url 'heart' %}" class="w3-bar-item w3-button">Heart</a>
    <a href="{% url 'liver' %}" class="w3-bar-item w3-button">Liver Disease</a>
    <a href="{% url 'kidney' %}" class="w3-bar-item w3-button">Kidney Disease</a>
    <a href="" class="w3-bar-item w3-button">Brain Tumor</a>

    
  
</div>

<br><br>


<div class="w3-container w3-card-4 w3-grey" style="width:50%;margin:auto;">
    <form  action="predict2">
      <div class="form-group">

        <label for="Pregnancies">No. of Pregnencies</label>
        <input class="form-control" type="number" id="Pregnancies" name="Pregnancies" required="required" placeholder="No. of Pregnencies">
      </div>
      <div class="form-group">
        <label for="Glucose">Glucose Level</label>
        <input class="form-control" type="number" step="any" id="Glucose" name="Present_Price" required="required" placeholder="Glucose Level">
      </div>
      <div class="form-group">
        <label for="BloodPressure">Current Blood Pressure</label>
        <input class="form-control" type="number" id="BloodPressure" name="BloodPressure" required="required" placeholder="Current Blood Pressure">
      </div>
      <div class="form-group">
        <label for="BMI">Enter the Body Mass Index</label>
        <input class="form-control" type="number" id="BMI" name="BMI" required="required" placeholder="Body Mass Index">
      </div>
      <div class="form-group">
        <label for="DiabetesPedigreeFunction">Diabetes Pedigree Function</label>
        <input class="form-control" type="number" id="DiabetesPedigreeFunction" name="DiabetesPedigreeFunction" required="required" placeholder="Diabetes Pedigree Function">
      </div>
      <div class="form-group">
        <label for="Age">Age</label>
        <input class="form-control" type="number" id="Age" name="Age" required="required" placeholder="Age">
      </div>
      
      
      
      <button type="submit" class="btn btn-danger">Predict</button>
    </form>
  </div>

    <div class="w3-row">

        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <a href="{% url 'home' %}"><i class=" fas fa-comments fa-stack-1x fa-inverse text-primary" ></i></a>
            </span>
            <h4 class="my-3">Chat</h4>
            
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Video</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <i class="fas fa-video fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="my-3">Video Call</h4>
            
            <p class="text-muted">click To have a video confrence with the Doctor.</p>
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            
                
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fas fa-video fa-stack-1x fa-inverse"></i>
                  </span> 
           
           
            <h4 class="my-3">Appointment</h4>
             
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
        </div>


    </div>
 
</div>

</body>
</html>

templates/heart.html
{% load static %}
{% load fontawesome_5 %}
 
<!DOCTYPE html>
<html>
    <head>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'w3.css' %}" rel="stylesheet" />

{% fontawesome_5_static %}
</head>
<body>


  <div class="w3-bar w3-black w3-padding-24" style="font-size:20px;">
    <a href="{% url 'home' %}" class="w3-bar-item w3-button" >Home</a>
    <a href="{% url 'diabetes' %}" class="w3-bar-item w3-button" >Diabetes</a>
    <a href="{% url 'heart' %}" class="w3-bar-item w3-button">Stroke</a>
    <a href="{% url 'liver' %}" class="w3-bar-item w3-button">Liver Disease</a>
    <a href="{% url 'kidney' %}" class="w3-bar-item w3-button">Kidney Disease</a>
    <a href="" class="w3-bar-item w3-button">Brain Tumor</a>

    
 
</div>

<br><br>

<div class="w3-container  w3-card" style="width:80%;margin: auto;">
	<br> <form action="predict">
   <div class="w3-row">
	 <div class="w3-half w3-container">
		 <div class="w3-container">
			<label>Age</label>
		<input type="text" class="w3-round w3-padding" name="age" placeholder="years" style="width: 80%;" required/>
		</div>
			
	<br>
 <div class="w3-container">
	<label>Sex</label>
	<select  name="sex" class="w3-round w3-padding" required style="width: 80%;" required>
   <option value="" disabled selected>Choose your option</option>
   <option value="1">Male</option>
   <option value="0">Female</option>
   
   </select>
 </div>    
			
 <br> 
	 <div class="w3-container">
			<label>Chest pain type</label>
			<select class="w3-round w3-padding" name="cp" style="width: 65%;" required>
			  <option value="0">typical angina</option>
			  <option value="1">atypical angina</option>
			  <option value="2">non-anginal pain</option>
			  <option value="3">asymptomatic</option>
			</select>
			</div>
			<br> 
			<div class="w3-container">
			<label>Resting blood pressure</label>
			<input
			  type="text"
			  class="w3-round w3-padding"
			  name="trestbps"
			  placeholder="in mm Hg"
			  style="width: 55%;" required/>
			</div>
			<br>
			<div class="w3-container">
			<label>Serum cholestoral</label>
			<input
			  type="text"
			  class="w3-round w3-padding"
			  name="chol"
			  placeholder="in mg/dl"
			  style="width: 61%;" required/>
			</div>
			<br>
			<div class="w3-container">
			<label>Fasting blood sugar > 120 mg/dl</label
			>
			<select class="w3-round w3-padding" name="fbs" style="width: 42%;" required>
			  <option value="0">Yes</option>
			  <option value="1">No</option>
			</select>
			</div>
			<br>
			<div class="w3-container">
		   <label class="">Resting ECG results</label>
		   <select class="w3-round w3-padding" name="restecg" style="width: 60%;" required>
			 <option value="0">normal</option>
			 <option value="1">
			 having ST-T wave abnormality
			 </option>
			 <option value="2">
			 left ventricular hyperthrophy
			 </option>
		   </select>
		   </div>
		 
   </div>
   
 
   
	   <div class="w3-half w3-container">
			<div class="w3-container">
			<label>Maximum heart rate achieved</label>
			<input type="text" class="w3-round w3-padding" name="thalach"  style="width: 60%;" required />
			</div>
			<br>
			<div class="w3-container">
			<label>Exercise induced angina</label>
			<select class="w3-round w3-padding" name="exang" style="width: 67%;" required>
			  <option value="1">Yes</option>
			  <option value="0">No</option>
			</select>
			</div>
			<br>
			<div class="w3-container">
			<label>ST depression induced by exercise relative to rest</label
			>
			<input type="text" class="w3-round w3-padding" name="oldpeak"  style="width: 35%;" required/>
			</div>
			<br>
			<div class="w3-container">
			<label >Slope - the slope of the peak exercise ST segment</label
			>
			<select name="slope" class="w3-round w3-padding" style="width: 35%;"required>
			  <option value="0">upsloping</option>
			  <option value="1">flat</option>
			  <option value="2">downsloping</option>
			</select>
			</div>
			<br>
			<div class="w3-container">
			<label >Number of major vessels (0-3) colored by flourosopy</label
			>
			<select class="w3-round w3-padding" name="ca" style="width: 30%;"  required>
			  <option value="0">0</option>
			  <option value="1">1</option>
			  <option value="2">2</option>
			  <option value="3">3</option>
			</select>
			</div>
			<br>
			<div class="w3-container">
			<label>Thalium (thal)</label>
			<select name="thal" class="w3-round w3-padding" style="width: 80%;" required>
			  <option value="0">normal</option>
			  <option value="1">fixed defect</option>
			  <option value="2">reversable defect</option>
			</select>
			</div>
			<br>
			<div class="w3-container">
		   <label>Age Category</label>
		   <select name="age_category" class="w3-round w3-padding" style="width: 80%;" required>
			 <option value="0">Youth</option>
			 <option value="1">Adult</option>
			 <option value="2">Old</option>
		   </select>
		   </div>
		   <br>
		   </div>
		 </div>
			
			 <br>
		 <div class="w3-container w3-center">
			<input type="submit" value="Predict" class="w3-teal w3-padding w3-round w3-border-teal">
		   
		   </div>
		   </form>
		   <br>
		  </div>
	 
<br><br><br><br>
<div class="w3-container w3-center w3-font-xxlarger"><h1 style="font-size:50px;"><b>Services</b></h1></div>
    <div class="w3-row">

        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <a href="{% url 'home' %}"><i class=" fas fa-comments fa-stack-1x fa-inverse text-primary" ></i></a>
            </span>
            <h4 class="my-3">Chat</h4>
            
            <p class="text-muted">click To chat with Us</p>
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Video</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <i class="fas fa-video fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="my-3">Video Call</h4>
            
            <p class="text-muted">click To have a video confrence with the Doctor.</p>
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            
                
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fas fa-video fa-stack-1x fa-inverse"></i>
                  </span> 
           
           
            <h4 class="my-3">Appointment</h4>
             
            <p class="text-muted">Book An Appointment with your Doctor.</p>
        </div>


    </div>
 
</div>

</body>
</html>

templates/home.html
{% load static %}
{% load fontawesome_5 %}
 
<!DOCTYPE html>
<html>
    <head>
<title>index</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'w3.css' %}" rel="stylesheet" />

{% fontawesome_5_static %}
</head>
<body>

<div class="w3-top">
  <div class="w3-bar w3-black w3-padding-24" style="font-size:20px;">
    <a href="{% url 'homepage' %}" class="w3-bar-item w3-button" >Home</a>
    <a href="{% url 'diabetes' %}" class="w3-bar-item w3-button" >Diabetes</a>
    <a href="{% url 'heart' %}" class="w3-bar-item w3-button">Heart</a>
    <a href="{% url 'liver' %}" class="w3-bar-item w3-button">Liver Disease</a>
    <a href="{% url 'kidney' %}" class="w3-bar-item w3-button">Kidney Disease</a>
    <a href="http://127.0.0.1:5000/" class="w3-bar-item w3-button">Brain Tumor</a>

  </div>
</div>

<br><br>

<div class="w3-container">
    <div>
        <img  class="w3-card-4 " class="w3-border w3-padding"  style="width: 100%;" src="{% static  'pocketdoc.jpg' %}">
    

    </div>
<br><br>
<div class="w3-container w3-center w3-font-xxlarger"><h1 style="font-size:50px;"><b>Services</b></h1></div>
    <br>
<div class="w3-row">


        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <a href="{% url 'accounts:register' %}"><i class=" fas fa-comments fa-stack-1x fa-inverse text-primary" ></i></a>
            </span>
            <h4 class="my-3">Chat</h4>
            
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Video</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <a href="{% url 'options' %}"><i class="fas fa-video fa-stack-1x fa-inverse"></i></a>
            </span>
            <h4 class="my-3">Video Call</h4>
        
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            
                
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <a href="{% url 'appointment' %}"> <i class="fas fa-handshake fa-stack-1x fa-inverse"></i></a>
                  </span> 
           
           
            <h4 class="my-3">Appointment</h4>
             
        </div>


    </div>
 <br><br>
</div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}WhatsApp{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'assets/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url 'chat' username=user.username%}">{{user.username}}</a></td>
                            </tr>
                            {% endfor %}

                            <!-- end -->
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

<style>
    @import url(https://fonts.googleapis.com/css?family=Roboto:300);

    .login-page {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
    }

    .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 360px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }

    .form input {
        font-family: "Roboto", sans-serif;
        outline: 0;
        background: #f2f2f2;
        width: 100%;
        border: 0;
        margin: 0 0 15px;
        padding: 15px;
        box-sizing: border-box;
        font-size: 14px;
    }

    .form button {
        font-family: "Roboto", sans-serif;
        text-transform: uppercase;
        outline: 0;
        background: #4CAF50;
        width: 100%;
        border: 0;
        padding: 15px;
        color: #FFFFFF;
        font-size: 14px;
        -webkit-transition: all 0.3 ease;
        transition: all 0.3 ease;
        cursor: pointer;
    }

    .form button:hover,
    .form button:active,
    .form button:focus {
        background: #43A047;
    }

    .form .message {
        margin: 15px 0 0;
        color: #b3b3b3;
        font-size: 12px;
    }

    .form .message a {
        color: #4CAF50;
        text-decoration: none;
    }

    .form .register-form {
        display: none;
    }

    .container {
        position: relative;
        z-index: 1;
        max-width: 300px;
        margin: 0 auto;
    }

    .container:before,
    .container:after {
        content: "";
        display: block;
        clear: both;
    }

    .container .info {
        margin: 50px auto;
        text-align: center;
    }

    .container .info h1 {
        margin: 0 0 15px;
        padding: 0;
        font-size: 36px;
        font-weight: 300;
        color: #1a1a1a;
    }

    .container .info span {
        color: #4d4d4d;
        font-size: 12px;
    }

    .container .info span a {
        color: #000000;
        text-decoration: none;
    }

    .container .info span .fa {
        color: #EF3B3A;
    }

    body {
        background: #76b852;
        /* fallback for old browsers */
        background: -webkit-linear-gradient(right, #76b852, #8DC26F);
        background: -moz-linear-gradient(right, #76b852, #8DC26F);
        background: -o-linear-gradient(right, #76b852, #8DC26F);
        background: linear-gradient(to left, #76b852, #8DC26F);
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>

<div class="login-page">
    <div class="form">
        <form class="login-form" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="username" name="username" />
            <input type="password" placeholder="password" name="password" />
            <button>login</button>
            <p class="message">Not registered? <a href="{% url 'accounts:register' %}">Create an account</a></p>
        </form>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register" class="btn btn-primary">
    </form>
    <p class="message">registered? <a href="{% url 'accounts:login' %}">Login</a></p>
</div>
{% endblock %}

templates/result.html
{% load static %}
{% load fontawesome_5 %}
 
<!DOCTYPE html>
<html>
    <head>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{% static 'w3.css' %}" rel="stylesheet" />

{% fontawesome_5_static %}
</head>
<body>


  <div class="w3-bar w3-black w3-padding-24" style="font-size:20px;">
    <a href="{% url 'home' %}" class="w3-bar-item w3-button" >Home</a>
    <a href="{% url 'diabetes' %}" class="w3-bar-item w3-button" >Diabetes</a>
    <a href="{% url 'heart' %}" class="w3-bar-item w3-button">Heart</a>
    <a href="{% url 'liver' %}" class="w3-bar-item w3-button">Liver Disease</a>
    <a href="{% url 'kidney' %}" class="w3-bar-item w3-button">Kidney Disease</a>
    <a href="" class="w3-bar-item w3-button">Brain Tumor</a>

    
 
</div>

<br><br>
<div class="w3-container w3-center">
    <h1>Heart Disease Detection Result</h1>
    </div>
    <br>
    
      {% if pred == 0 %}
      
     
    <div class="w3-container w3-pale-blue w3-leftbar w3-border-blue">
        <p>Good,you are healthy,keep it up by less sugar.</p>
      </div>
      {% elif pred == 1  %}
        
        <div class="w3-container w3-center w3-round">

        
          <div class="w3-container w3-light-grey w3-border" style="width: 20%;height:300px;margin: auto;">
            <h2>You are suffering from heart disease,you need to see a doctor.</h2>
          </div> 
      
    
       {% endif%}
    
       
    
      
    </div>
    <br>
    <div class="w3-container w3-center">
      <button  class="w3-teal w3-center w3-padding w3-round w3-border-teal"><a href="{% url 'index' %}">back</a></button>
      </div>   

<br><br>
<div class="w3-container w3-center w3-font-xxlarger"><h1 style="font-size:50px;"><b>Services</b></h1></div>
    <div class="w3-row">

        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <a href="{% url 'home' %}"><i class=" fas fa-comments fa-stack-1x fa-inverse text-primary" ></i></a>
            </span>
            <h4 class="my-3">Chat</h4>
            
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Video</h1>
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x "></i>
                <i class="fas fa-video fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="my-3">Video Call</h4>
            
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
        </div>
        <div class="w3-third w3-container w3-center">
            <h1>Chat</h1>
            
                
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fas fa-video fa-stack-1x fa-inverse"></i>
                  </span> 
           
           
            <h4 class="my-3">Appointment</h4>
             
            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
        </div>


    </div>
 
</div>

</body>
</html>

templates/result1.html
{{pred}}

templates/result2.html
{{pred}}

templates/result3.html
{{pred}}